### ISSUE TITLE
BUG: Anything using the helper.py with torch 1.13.1 fails

### ISSUE THREAD

**Issue by A7exSchin** [Forschungsprojekt-Informatik/CompGCN#6]
Anything thats tries to use the helper.py functions ccorr, conj, ... with torch 1.13.1 instead of 1.4 fails with different errors, as upgraded torch has moved functions.

**Comment by 1Maxnet1** [comment]
Could you give an example command and report what happens when you execute it ?

**Comment by JWG-1** [comment]
fixed, problem appeared because of version change of pytorch, the problem appeared when using the circular correlation

**Comment by 1Maxnet1** [comment]
> fixed, problem appeared because of version change of pytorch, the problem appeared when using the circular correlation

Could you also describe how you fixed it? I couldn't find a related PR so it might make sense to keep the issue open until the solution is available in development

**Comment by JWG-1** [comment]
the problem was in that in the newer version of pytorch the implementation of rfft and irfft are in torch.fft.xxx and that they changed outputted to a complex Tensor and not a 2 dimensional tensor. The solution was to simpley change the implentation of  the helper functions conj(), com_mul(), cconv() and corr(). I committed the solution already to the development branch.

**Comment by 1Maxnet1** [comment]
> the problem was in that in the newer version of pytorch the implementation of rfft and irfft are in torch.fft.xxx and that they changed outputted to a complex Tensor and not a 2 dimensional tensor. The solution was to simpley change the implentation of the helper functions conj(), com_mul(), cconv() and corr(). I committed the solution already to the development branch.

Ok then. As we defined in https://github.com/Forschungsprojekt-Informatik/CompGCN/wiki/Branching-model please do not commit or push directly to the development branch.
